# Read the Docs-Konfigurationsdatei für HTML/CSS/JavaScript-Projekte
# Siehe hier für Details
version: 2

# Setze das Betriebssystem, die Python-Version und andere benötigte Tools
build:
  os: ubuntu-22.04
  tools:
    - python: "3.12"

# Optional: Deklariere die Python-Anforderungen für den Build (falls nicht benötigt, entferne diese Zeilen)
python:
  install:
    - requirements: docs/requirements.txt

# Optional: Füge zusätzliche Formate hinzu (z. B. PDF, ePub)
formats:
  - pdf
  - epub
