# Read the Docs-Konfigurationsdatei f체r HTML/CSS/JavaScript-Projekte
# Siehe hier f체r Details
version: 2

build:
  os: "ubuntu-20.04"
  tools: sphinx  # Beispiel: Verwende Sphinx als Build-Tool

# Optional: F체ge zus채tzliche Formate hinzu (z. B. PDF, ePub)
formats:
  - pdf
  - epub
