# Read the Docs-Konfigurationsdatei für HTML/CSS/JavaScript-Projekte
# Siehe hier für Details
version: 2

# Setze das Betriebssystem, die Python-Version und andere benötigte Tools
build:
  os: windows
  



# Optional: Füge zusätzliche Formate hinzu (z. B. PDF, ePub)
formats:
  - pdf
  - epub
