# Read the Docs-Konfigurationsdatei f체r HTML/CSS/JavaScript-Projekte
# Siehe hier f체r Details
version: 2

build:
  commands:
    - make html


# Optional: F체ge zus채tzliche Formate hinzu (z. B. PDF, ePub)
formats:
  - pdf
  - epub
