# Read the Docs-Konfigurationsdatei f체r HTML/CSS/JavaScript-Projekte
# Siehe hier f체r Details
version: 2

build:
  os: "ubuntu-lts-latest"
  commands:
    - pip install -r requirements.txt
    - make html

# Optional: F체ge zus채tzliche Formate hinzu (z. B. PDF, ePub)
formats:
  - pdf
  - epub
